language: java
jdk:
  - openjdk8

os:
  - linux
  dist:
  - xenial # other choices are 'trusty' or 'precise'

branches:
  only:
    - master

# Travis CI 서버의 Cache 활성화
cache:
  directories:
    - '$HOME/.m2/repository'

script: "sudo ./mvnw clean package && java -jar target/*.jar"